# Generated by Django 5.0.3 on 2024-04-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='HousePriceFactor',
        ),
        migrations.RenameField(
            model_name='housepricefactor',
            old_name='salepric',
            new_name='saleprice',
        ),
    ]
