# Generated by Django 5.0.3 on 2024-04-20 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_price_housepricefactor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepricefactor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 5, 29, 26, 131294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='housepricefactor',
            table='house_price_factor',
        ),
    ]
